### ISSUE TITLE
Error upload photo in avatar code: 'ERR_INVALID_ARG_TYPE'

### ISSUE THREAD

**Issue by onlyreynaldo** [onlyreynaldo/eleventh-starting-back-end#6]
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at validateString (internal/validators.js:120:11)
    at Object.resolve (path.js:980:7)
    at DiskStorageProvider.<anonymous> (/Users/reynaldo/Developer/Rocketseat/Eleventh/04-starting-back-end/src/shared/container/providers/StorageProvider/implementations/DiskStorageProvider.ts:9:12)
    at step (/Users/reynaldo/Developer/Rocketseat/Eleventh/04-starting-back-end/src/shared/container/providers/StorageProvider/implementations/DiskStorageProvider.ts:33:23)

**Comment by onlyreynaldo** [comment]
The error occurred because the multer was not configured well in our user route, as we used the temporary configuration, then when saving the photo, I could not find the place to look for it because it was not configured,

Previously this configuration was direct, completing the Storage values ​​in Multer, but in this last change it was altered by moving this configuration in an Object called multer.
